- name: Use http redirector for apt
  replace:
    dest: /etc/apt/sources.list
    regexp: 'ftp.us'
    replace: 'httpredir'
  tags: apt,localization

- name: Install standard software
  apt:
    update_cache: yes
    name:
      - aptitude # required for upgrade mode 'full'
      - tmux
      - htop
      - vim
    state: present
  tags: apt

- name: Upgrade all software
  apt:
    upgrade: full
  tags: apt

- name: Copy the public key of the user who is running ansible to the remote machine
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags: ssh

- name: Start the ssh service
  systemd:
    name: ssh
    state: started
    enabled: true
  tags: ssh

- name: No stupid login message
  file:
    path:  "/home/{{ ansible_user }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  "0755"
  tags: user

- name: Set keyboard layout
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
  tags: localization

- name: Add the user '{{ ansible_user }}' to the list of sudoers
  copy:
    src: sudoers
    dest: "/etc/sudoers.d/{{ ansible_user }}"
    owner: root
    group: root
    mode: "0640"
  tags: user,security

- name: Configure tmux
  copy:
    src: tmux.conf
    dest: "/home/{{ ansible_user }}/.tmux.conf"
    mode: 0644
  tags: tmux
